-- Complete Multi-Room Component Library
-- Generated from extracted components
-- Bedrooms, Bathrooms, Living Rooms, Offices, Dining Rooms, and Universal Components

-- Temporarily disable RLS
ALTER TABLE public.components DISABLE ROW LEVEL SECURITY;

-- Insert all non-kitchen components
INSERT INTO public.components (
  component_id, name, type, width, depth, height, color, category, room_types, icon_name, description, version, deprecated, metadata, tags
) VALUES 
('counter-top-horizontal', 'Counter Top Horizontal', 'counter-top', 300, 60, 4, '#D2B48C', 'counter-tops', ARRAY['kitchen', 'bedroom', 'bathroom', 'living-room', 'office', 'dining-room', 'dressing-room', 'utility', 'under-stairs', 'media-wall', 'internal-doors', 'flooring'], 'Square', 'Horizontal counter top - 300cm x 60cm x 4cm (left-to-right)', '1.0.0', false, '{}', '{}'),
('counter-top-vertical', 'Counter Top Vertical', 'counter-top', 60, 300, 4, '#D2B48C', 'counter-tops', ARRAY['kitchen', 'bedroom', 'bathroom', 'living-room', 'office', 'dining-room', 'dressing-room', 'utility', 'under-stairs', 'media-wall', 'internal-doors', 'flooring'], 'Square', 'Vertical counter top - 60cm x 300cm x 4cm (front-to-back)', '1.0.0', false, '{}', '{}'),
('counter-top-square', 'Counter Top Square', 'counter-top', 60, 60, 4, '#D2B48C', 'counter-tops', ARRAY['kitchen', 'bedroom', 'bathroom', 'living-room', 'office', 'dining-room', 'dressing-room', 'utility', 'under-stairs', 'media-wall', 'internal-doors', 'flooring'], 'Square', 'Square counter top - 60cm x 60cm x 4cm', '1.0.0', false, '{}', '{}'),
('counter-top-corner', 'Counter Top Corner', 'counter-top', 90, 90, 4, '#D2B48C', 'counter-tops', ARRAY['kitchen', 'bedroom', 'bathroom', 'living-room', 'office', 'dining-room', 'dressing-room', 'utility', 'under-stairs', 'media-wall', 'internal-doors', 'flooring'], 'Square', 'L-shaped corner counter top - 90cm x 90cm x 4cm', '1.0.0', false, '{}', '{}'),
('end-panel-base', 'End Panel Base Unit', 'end-panel', 1.8, 60, 90, '#8B4513', 'end-panels', ARRAY['kitchen', 'bedroom', 'bathroom', 'living-room', 'office', 'dining-room', 'dressing-room', 'utility', 'under-stairs', 'media-wall', 'internal-doors', 'flooring'], 'Square', 'Base unit end panel - 1.8cm x 60cm x 90cm', '1.0.0', false, '{}', '{}'),
('end-panel-full-height', 'End Panel Full Height', 'end-panel', 1.8, 60, 200, '#8B4513', 'end-panels', ARRAY['kitchen', 'bedroom', 'bathroom', 'living-room', 'office', 'dining-room', 'dressing-room', 'utility', 'under-stairs', 'media-wall', 'internal-doors', 'flooring'], 'Square', 'Full height end panel - 1.8cm x 60cm x 200cm', '1.0.0', false, '{}', '{}'),
('double-bed', 'Double Bed', 'appliance', 140, 140, 200, '#8B4513', 'bedroom-furniture', ARRAY['bedroom', 'master-bedroom', 'guest-bedroom'], 'Bed', 'Standard double bed frame', '1.0.0', false, '{}', '{}'),
('king-bed', 'King Size Bed', 'appliance', 160, 160, 200, '#8B4513', 'bedroom-furniture', ARRAY['bedroom', 'master-bedroom', 'guest-bedroom'], 'Bed', 'King size bed frame', '1.0.0', false, '{}', '{}'),
('wardrobe-2door', '2 Door Wardrobe', 'cabinet', 100, 100, 60, '#654321', 'bedroom-storage', ARRAY['bedroom', 'master-bedroom', 'guest-bedroom'], 'Shirt', 'Two door wardrobe', '1.0.0', false, '{}', '{}'),
('wardrobe-3door', '3 Door Wardrobe', 'cabinet', 150, 150, 60, '#654321', 'bedroom-storage', ARRAY['bedroom', 'master-bedroom', 'guest-bedroom'], 'Shirt', 'Three door wardrobe', '1.0.0', false, '{}', '{}'),
('chest-drawers', 'Chest of Drawers', 'cabinet', 80, 80, 40, '#654321', 'bedroom-storage', ARRAY['bedroom', 'master-bedroom', 'guest-bedroom'], 'Archive', 'Four drawer chest', '1.0.0', false, '{}', '{}'),
('bedside-table', 'Bedside Table', 'cabinet', 40, 40, 40, '#654321', 'bedroom-storage', ARRAY['bedroom', 'master-bedroom', 'guest-bedroom'], 'Box', 'Bedside table with drawer', '1.0.0', false, '{}', '{}'),
('vanity-unit-60', 'Vanity Unit 60cm', 'cabinet', 60, 60, 60, '#F5F5DC', 'bathroom-vanities', ARRAY['bathroom', 'ensuite'], 'Bath', 'Wall-hung vanity unit with basin', '1.0.0', false, '{}', '{}'),
('vanity-unit-80', 'Vanity Unit 80cm', 'cabinet', 80, 80, 60, '#F5F5DC', 'bathroom-vanities', ARRAY['bathroom', 'ensuite'], 'Bath', 'Wall-hung vanity unit with basin', '1.0.0', false, '{}', '{}'),
('toilet', 'Toilet', 'appliance', 40, 40, 60, '#FFFFFF', 'bathroom-fixtures', ARRAY['bathroom', 'ensuite'], 'Home', 'Wall-hung toilet', '1.0.0', false, '{}', '{}'),
('shower-tray', 'Shower Tray', 'appliance', 90, 90, 90, '#E6E6FA', 'bathroom-fixtures', ARRAY['bathroom', 'ensuite'], 'Waves', 'Square shower tray', '1.0.0', false, '{}', '{}'),
('bathtub', 'Bathtub', 'appliance', 170, 170, 70, '#FFFFFF', 'bathroom-fixtures', ARRAY['bathroom', 'ensuite'], 'Bath', 'Standard bathtub', '1.0.0', false, '{}', '{}'),
('tv-unit-120', 'TV Unit 120cm', 'cabinet', 120, 120, 40, '#2F4F4F', 'media-furniture', ARRAY['living-room'], 'Tv', 'Low TV cabinet unit', '1.0.0', false, '{}', '{}'),
('tv-unit-160', 'TV Unit 160cm', 'cabinet', 160, 160, 40, '#2F4F4F', 'media-furniture', ARRAY['living-room'], 'Tv', 'Wide TV cabinet unit', '1.0.0', false, '{}', '{}'),
('media-shelving', 'Media Shelving', 'cabinet', 60, 60, 120, '#2F4F4F', 'media-storage', ARRAY['living-room'], 'Box', 'Tall media shelving unit', '1.0.0', false, '{}', '{}'),
('media-cabinet', 'Media Cabinet', 'cabinet', 80, 80, 80, '#2F4F4F', 'media-storage', ARRAY['living-room'], 'Archive', 'Square media storage cabinet', '1.0.0', false, '{}', '{}'),
('hardwood-section', 'Hardwood Section', 'appliance', 100, 100, 100, '#DEB887', 'flooring-materials', ARRAY['dining-room'], 'Grid3X3', 'Hardwood flooring section', '1.0.0', false, '{}', '{}'),
('tile-section', 'Tile Section', 'appliance', 100, 100, 100, '#D3D3D3', 'flooring-materials', ARRAY['dining-room'], 'Square', 'Ceramic tile section', '1.0.0', false, '{}', '{}'),
('carpet-section', 'Carpet Section', 'appliance', 100, 100, 100, '#8FBC8F', 'flooring-materials', ARRAY['dining-room'], 'Sofa', 'Carpet flooring section', '1.0.0', false, '{}', '{}'),
('modern-sofa', 'Modern Sofa', 'appliance', 200, 200, 80, '#3A6EA5', 'living-room-furniture', ARRAY['living-room'], 'Sofa', 'Contemporary 3-seater sofa', '1.0.0', false, '{}', '{}'),
('armchair', 'Armchair', 'appliance', 80, 80, 80, '#3A6EA5', 'living-room-furniture', ARRAY['living-room'], 'Sofa', 'Comfortable single armchair', '1.0.0', false, '{}', '{}'),
('coffee-table', 'Coffee Table', 'appliance', 120, 120, 60, '#8B4513', 'living-room-furniture', ARRAY['living-room'], 'RectangleHorizontal', 'Rectangular coffee table', '1.0.0', false, '{}', '{}'),
('entertainment-wall-unit', 'Entertainment Wall Unit', 'cabinet', 300, 300, 220, '#2F4F4F', 'living-room-built-ins', ARRAY['living-room'], 'Tv', 'Custom floor-to-ceiling entertainment wall system', '1.0.0', false, '{}', '{}'),
('media-console-floating', 'Floating Media Console', 'cabinet', 180, 180, 40, '#2F4F4F', 'living-room-built-ins', ARRAY['living-room'], 'Tv', 'Wall-mounted floating entertainment unit', '1.0.0', false, '{}', '{}'),
('corner-entertainment-unit', 'Corner Entertainment Unit', 'cabinet', 120, 120, 180, '#2F4F4F', 'living-room-built-ins', ARRAY['living-room'], 'Square', 'L-shaped corner entertainment unit maximizing space', '1.0.0', false, '{}', '{}'),
('floor-to-ceiling-bookshelf', 'Floor-to-Ceiling Bookshelf', 'cabinet', 80, 80, 240, '#8B4513', 'living-room-shelving', ARRAY['living-room'], 'Archive', 'Tall custom bookshelf with adjustable shelving', '1.0.0', false, '{}', '{}'),
('wall-mounted-shelves-wide', 'Wide Wall Shelves', 'cabinet', 200, 200, 30, '#F5DEB3', 'living-room-shelving', ARRAY['living-room'], 'RectangleHorizontal', 'Wide wall-mounted display shelves', '1.0.0', false, '{}', '{}'),
('recessed-bookshelves', 'Recessed Bookshelves', 'cabinet', 100, 100, 180, '#8B4513', 'living-room-shelving', ARRAY['living-room'], 'Archive', 'Built-in recessed bookshelf alcove', '1.0.0', false, '{}', '{}'),
('sectional-sofa-left-arm', 'Sectional Sofa (Left Arm)', 'appliance', 280, 280, 90, '#3A6EA5', 'living-room-furniture', ARRAY['living-room'], 'Sofa', 'Large left-arm sectional sofa', '1.0.0', false, '{}', '{}'),
('loveseat-sofa', 'Loveseat Sofa', 'appliance', 140, 140, 80, '#3A6EA5', 'living-room-furniture', ARRAY['living-room'], 'Sofa', 'Compact 2-seater loveseat', '1.0.0', false, '{}', '{}'),
('chaise-lounge', 'Chaise Lounge', 'appliance', 160, 160, 70, '#3A6EA5', 'living-room-furniture', ARRAY['living-room'], 'Sofa', 'Comfortable chaise lounge chair', '1.0.0', false, '{}', '{}'),
('ottoman-storage-large', 'Large Storage Ottoman', 'cabinet', 100, 100, 50, '#6B8E23', 'living-room-storage', ARRAY['living-room'], 'Archive', 'Large upholstered ottoman with internal storage', '1.0.0', false, '{}', '{}'),
('console-table-storage', 'Console Table with Storage', 'cabinet', 120, 120, 80, '#8B4513', 'living-room-storage', ARRAY['living-room'], 'Archive', 'Console table with drawers and cabinets', '1.0.0', false, '{}', '{}'),
('floor-lamp-modern', 'Modern Floor Lamp', 'appliance', 40, 40, 160, '#C0C0C0', 'living-room-props', ARRAY['living-room'], 'Zap', 'Contemporary floor lamp with adjustable height', '1.0.0', false, '{}', '{}'),
('area-rug-large', 'Large Area Rug', 'appliance', 300, 300, 200, '#8B4513', 'living-room-props', ARRAY['living-room'], 'Sofa', 'Large patterned area rug for living room', '1.0.0', false, '{}', '{}'),
('office-desk', 'Office Desk', 'appliance', 150, 150, 75, '#2F4F4F', 'office-furniture', ARRAY['office', 'bedroom', 'living-room'], 'RectangleHorizontal', 'Standard office desk', '1.0.0', false, '{}', '{}'),
('office-chair', 'Office Chair', 'appliance', 60, 60, 60, '#2F4F4F', 'office-furniture', ARRAY['office', 'bedroom', 'living-room'], 'Sofa', 'Ergonomic office chair', '1.0.0', false, '{}', '{}'),
('bookshelf', 'Bookshelf', 'cabinet', 100, 100, 200, '#8B4513', 'office-furniture', ARRAY['office', 'bedroom', 'living-room'], 'Archive', 'Tall bookshelf', '1.0.0', false, '{}', '{}'),
('executive-desk', 'Executive Desk', 'appliance', 180, 180, 80, '#8B4513', 'office-furniture', ARRAY['office'], 'RectangleHorizontal', 'Large executive desk with multiple drawers', '1.0.0', false, '{}', '{}'),
('l-shaped-desk', 'L-Shaped Desk', 'appliance', 160, 160, 140, '#8B4513', 'office-furniture', ARRAY['office'], 'RectangleHorizontal', 'Corner L-shaped desk maximizing workspace', '1.0.0', false, '{}', '{}'),
('standing-desk', 'Height Adjustable Desk', 'appliance', 160, 160, 80, '#2F4F4F', 'office-furniture', ARRAY['office'], 'RectangleHorizontal', 'Electric height-adjustable standing desk', '1.0.0', false, '{}', '{}'),
('filing-cabinet-4drawer', '4-Drawer Filing Cabinet', 'cabinet', 45, 45, 130, '#2F4F4F', 'office-storage', ARRAY['office'], 'Archive', 'Tall metal filing cabinet with lock', '1.0.0', false, '{}', '{}'),
('storage-credenza', 'Storage Credenza', 'cabinet', 180, 180, 60, '#8B4513', 'office-storage', ARRAY['office'], 'Archive', 'Low credenza with multiple storage compartments', '1.0.0', false, '{}', '{}'),
('bookshelf-barrister', 'Barrister Bookshelf', 'cabinet', 80, 80, 180, '#8B4513', 'office-shelving', ARRAY['office'], 'Archive', 'Traditional barrister bookcase with glass doors', '1.0.0', false, '{}', '{}'),
('wall-mounted-shelves-office', 'Wall-Mounted Office Shelves', 'cabinet', 150, 150, 30, '#F5DEB3', 'office-shelving', ARRAY['office'], 'RectangleHorizontal', 'Wall-mounted shelves above desk', '1.0.0', false, '{}', '{}'),
('desk-lamp-led', 'LED Desk Lamp', 'appliance', 25, 25, 40, '#C0C0C0', 'office-props', ARRAY['office'], 'Zap', 'Modern LED desk lamp with adjustable arm', '1.0.0', false, '{}', '{}'),
('whiteboard-wall', 'Wall-Mounted Whiteboard', 'appliance', 120, 120, 90, '#FFFFFF', 'office-props', ARRAY['office'], 'RectangleHorizontal', 'Magnetic whiteboard for brainstorming', '1.0.0', false, '{}', '{}'),
('dressing-table', 'Dressing Table', 'appliance', 120, 120, 50, '#8B4513', 'bedroom-furniture', ARRAY['bedroom', 'master-bedroom', 'guest-bedroom'], 'RectangleHorizontal', 'Bedroom dressing table with mirror', '1.0.0', false, '{}', '{}'),
('bedroom-ottoman', 'Ottoman', 'appliance', 60, 60, 60, '#6B8E23', 'bedroom-furniture', ARRAY['bedroom', 'master-bedroom', 'guest-bedroom'], 'Sofa', 'Bedroom ottoman/seat', '1.0.0', false, '{}', '{}'),
('king-bed-storage', 'King Bed with Storage', 'appliance', 180, 180, 200, '#8B4513', 'bedroom-furniture', ARRAY['bedroom', 'master-bedroom'], 'Bed', 'King size bed with under-bed storage drawers', '1.0.0', false, '{}', '{}'),
('super-king-bed', 'Super King Bed', 'appliance', 200, 200, 200, '#8B4513', 'bedroom-furniture', ARRAY['bedroom', 'master-bedroom'], 'Bed', 'Super king size bed frame', '1.0.0', false, '{}', '{}'),
('single-bed', 'Single Bed', 'appliance', 100, 100, 200, '#8B4513', 'bedroom-furniture', ARRAY['bedroom', 'guest-bedroom'], 'Bed', 'Single bed for guest rooms or children', '1.0.0', false, '{}', '{}'),
('bunk-bed-system', 'Bunk Bed System', 'appliance', 100, 100, 180, '#8B4513', 'bedroom-furniture', ARRAY['bedroom', 'guest-bedroom'], 'Bed', 'Two-tier bunk bed with storage underneath', '1.0.0', false, '{}', '{}'),
('upholstered-bench', 'Upholstered Storage Bench', 'appliance', 120, 120, 50, '#6B8E23', 'bedroom-furniture', ARRAY['bedroom', 'master-bedroom'], 'Sofa', 'End-of-bed bench with internal storage', '1.0.0', false, '{}', '{}'),
('reading-chair', 'Reading Chair', 'appliance', 70, 70, 80, '#8B4513', 'bedroom-furniture', ARRAY['bedroom', 'master-bedroom'], 'Sofa', 'Comfortable armchair for bedroom reading nook', '1.0.0', false, '{}', '{}'),
('wardrobe-walk-in', 'Walk-in Wardrobe Unit', 'cabinet', 200, 200, 60, '#654321', 'bedroom-storage', ARRAY['bedroom', 'master-bedroom'], 'Shirt', 'Custom walk-in wardrobe with hanging rails and shelves', '1.0.0', false, '{}', '{}'),
('wardrobe-built-in', 'Built-in Wardrobe', 'cabinet', 240, 240, 60, '#654321', 'bedroom-storage', ARRAY['bedroom', 'master-bedroom', 'guest-bedroom'], 'Shirt', 'Floor-to-ceiling built-in wardrobe system', '1.0.0', false, '{}', '{}'),
('wardrobe-corner', 'Corner Wardrobe', 'cabinet', 120, 120, 120, '#654321', 'bedroom-storage', ARRAY['bedroom', 'master-bedroom'], 'Square', 'L-shaped corner wardrobe maximizing space', '1.0.0', false, '{}', '{}'),
('wardrobe-sliding-door', 'Sliding Door Wardrobe', 'cabinet', 180, 180, 60, '#654321', 'bedroom-storage', ARRAY['bedroom', 'master-bedroom', 'guest-bedroom'], 'Shirt', 'Space-saving sliding door wardrobe system', '1.0.0', false, '{}', '{}'),
('bed-storage-drawers', 'Bed Storage Drawers', 'cabinet', 160, 160, 40, '#8B4513', 'bedroom-storage', ARRAY['bedroom', 'master-bedroom', 'guest-bedroom'], 'Archive', 'Under-bed storage drawers for seasonal items', '1.0.0', false, '{}', '{}'),
('tallboy-6-drawer', 'Tallboy Chest', 'cabinet', 50, 50, 120, '#654321', 'bedroom-storage', ARRAY['bedroom', 'master-bedroom', 'guest-bedroom'], 'Archive', 'Narrow 6-drawer tallboy for tight spaces', '1.0.0', false, '{}', '{}'),
('shoe-storage-tower', 'Shoe Storage Tower', 'cabinet', 60, 60, 120, '#654321', 'bedroom-storage', ARRAY['bedroom', 'master-bedroom', 'guest-bedroom'], 'Box', 'Vertical shoe storage with adjustable shelves', '1.0.0', false, '{}', '{}'),
('bed-head-unit', 'Bed Head Storage Unit', 'cabinet', 160, 160, 30, '#8B4513', 'bedroom-storage', ARRAY['bedroom', 'master-bedroom', 'guest-bedroom'], 'Archive', 'Custom bed head unit with integrated storage', '1.0.0', false, '{}', '{}'),
('floating-bedside', 'Floating Bedside Cabinet', 'cabinet', 50, 50, 40, '#8B4513', 'bedroom-storage', ARRAY['bedroom', 'master-bedroom', 'guest-bedroom'], 'Box', 'Wall-mounted floating bedside cabinet', '1.0.0', false, '{}', '{}'),
('corner-shelving', 'Corner Display Shelving', 'cabinet', 60, 60, 180, '#F5DEB3', 'bedroom-storage', ARRAY['bedroom', 'master-bedroom'], 'Square', 'Corner shelving unit for books and decor', '1.0.0', false, '{}', '{}'),
('bedside-lamp', 'Bedside Lamp', 'appliance', 25, 25, 50, '#F5F5DC', 'bedroom-props', ARRAY['bedroom', 'master-bedroom', 'guest-bedroom'], 'Zap', 'Table lamp for bedside lighting', '1.0.0', false, '{}', '{}'),
('wall-mirror-oval', 'Oval Wall Mirror', 'appliance', 60, 60, 80, '#C0C0C0', 'bedroom-props', ARRAY['bedroom', 'master-bedroom', 'guest-bedroom'], 'RectangleHorizontal', 'Oval framed wall mirror', '1.0.0', false, '{}', '{}'),
('bedroom-rug-large', 'Large Bedroom Rug', 'appliance', 250, 250, 180, '#8B4513', 'bedroom-props', ARRAY['bedroom', 'master-bedroom'], 'Sofa', 'Large area rug for bedroom floor', '1.0.0', false, '{}', '{}'),
('curtains-floor-length', 'Floor Length Curtains', 'appliance', 100, 100, 250, '#F5F5DC', 'bedroom-props', ARRAY['bedroom', 'master-bedroom', 'guest-bedroom'], 'RectangleHorizontal', 'Floor-to-ceiling window curtains', '1.0.0', false, '{}', '{}'),
('walk-in-wardrobe-system', 'Walk-in Wardrobe System', 'cabinet', 300, 300, 60, '#654321', 'dressing-storage', ARRAY['dressing-room'], 'Shirt', 'Complete walk-in wardrobe system with hanging rails', '1.0.0', false, '{}', '{}'),
('wardrobe-island-unit', 'Wardrobe Island Unit', 'cabinet', 120, 120, 80, '#654321', 'dressing-storage', ARRAY['dressing-room'], 'Archive', 'Central island unit with drawers and storage', '1.0.0', false, '{}', '{}'),
('shoe-storage-tower-dressing', 'Shoe Storage Tower', 'cabinet', 60, 60, 200, '#654321', 'dressing-storage', ARRAY['dressing-room'], 'Box', 'Tall shoe storage with automatic shutters', '1.0.0', false, '{}', '{}'),
('jewelry-armoire-large', 'Jewelry Armoire', 'cabinet', 50, 50, 150, '#654321', 'dressing-storage', ARRAY['dressing-room'], 'Archive', 'Large jewelry armoire with compartments', '1.0.0', false, '{}', '{}'),
('dressing-table-vanity-large', 'Large Vanity Dressing Table', 'cabinet', 160, 160, 50, '#8B4513', 'dressing-furniture', ARRAY['dressing-room'], 'RectangleHorizontal', 'Large vanity table with integrated lighting', '1.0.0', false, '{}', '{}'),
('dressing-bench-storage-large', 'Storage Dressing Bench', 'appliance', 120, 120, 50, '#8B4513', 'dressing-furniture', ARRAY['dressing-room'], 'Sofa', 'Upholstered bench with under-seat storage', '1.0.0', false, '{}', '{}'),
('full-length-mirror-stand-large', 'Full-Length Mirror', 'appliance', 60, 60, 180, '#C0C0C0', 'dressing-props', ARRAY['dressing-room'], 'RectangleHorizontal', 'Floor-standing full-length mirror', '1.0.0', false, '{}', '{}'),
('dressing-room-mirror-lighted', 'Lighted Dressing Mirror', 'appliance', 80, 80, 100, '#C0C0C0', 'dressing-props', ARRAY['dressing-room'], 'Zap', 'Hollywood-style lighted vanity mirror', '1.0.0', false, '{}', '{}'),
('vanity-double-120', 'Double Vanity 120cm', 'cabinet', 120, 120, 60, '#F5F5DC', 'bathroom-vanities', ARRAY['bathroom', 'ensuite'], 'Bath', 'His & hers double vanity unit with integrated storage', '1.0.0', false, '{}', '{}'),
('vanity-floating-100', 'Floating Vanity 100cm', 'cabinet', 100, 100, 50, '#F5F5DC', 'bathroom-vanities', ARRAY['bathroom', 'ensuite'], 'Bath', 'Wall-mounted floating vanity with open shelving', '1.0.0', false, '{}', '{}'),
('vanity-corner-unit', 'Corner Vanity Unit', 'cabinet', 80, 80, 80, '#F5F5DC', 'bathroom-vanities', ARRAY['bathroom', 'ensuite'], 'Square', 'L-shaped corner vanity maximizing bathroom space', '1.0.0', false, '{}', '{}'),
('vanity-compact-45', 'Compact Vanity 45cm', 'cabinet', 45, 45, 60, '#F5F5DC', 'bathroom-vanities', ARRAY['bathroom', 'ensuite'], 'Bath', 'Narrow vanity for powder rooms or small bathrooms', '1.0.0', false, '{}', '{}'),
('bathroom-linen-cupboard', 'Linen Cupboard', 'cabinet', 60, 60, 180, '#F5F5DC', 'bathroom-storage', ARRAY['bathroom', 'ensuite'], 'Archive', 'Tall linen storage cupboard with adjustable shelves', '1.0.0', false, '{}', '{}'),
('bathroom-mirror-cabinet', 'Illuminated Mirror Cabinet', 'cabinet', 70, 70, 80, '#C0C0C0', 'bathroom-storage', ARRAY['bathroom', 'ensuite'], 'RectangleHorizontal', 'Mirror-fronted cabinet with integrated lighting', '1.0.0', false, '{}', '{}'),
('bathroom-towel-rack', 'Towel Storage Rack', 'cabinet', 80, 80, 40, '#F5F5DC', 'bathroom-storage', ARRAY['bathroom', 'ensuite'], 'Archive', 'Wall-mounted towel storage with baskets', '1.0.0', false, '{}', '{}'),
('bathroom-under-sink-storage', 'Under-Sink Pull-Out Storage', 'cabinet', 60, 60, 80, '#F5F5DC', 'bathroom-storage', ARRAY['bathroom', 'ensuite'], 'Archive', 'Custom under-sink storage with pull-out drawers', '1.0.0', false, '{}', '{}'),
('toilet-compact', 'Compact Toilet', 'appliance', 35, 35, 60, '#FFFFFF', 'bathroom-fixtures', ARRAY['bathroom', 'ensuite'], 'Home', 'Space-saving compact toilet design', '1.0.0', false, '{}', '{}'),
('shower-enclosure-rectangular', 'Rectangular Shower Enclosure', 'appliance', 80, 80, 200, '#E6E6FA', 'bathroom-fixtures', ARRAY['bathroom', 'ensuite'], 'Waves', 'Walk-in shower enclosure with frameless glass', '1.0.0', false, '{}', '{}'),
('shower-enclosure-corner', 'Corner Shower Enclosure', 'appliance', 90, 90, 90, '#E6E6FA', 'bathroom-fixtures', ARRAY['bathroom', 'ensuite'], 'Square', 'Corner shower enclosure with sliding doors', '1.0.0', false, '{}', '{}'),
('freestanding-bathtub', 'Freestanding Bathtub', 'appliance', 170, 170, 75, '#FFFFFF', 'bathroom-fixtures', ARRAY['bathroom', 'ensuite'], 'Bath', 'Classic freestanding roll-top bathtub', '1.0.0', false, '{}', '{}'),
('walk-in-bathtub', 'Walk-in Bathtub', 'appliance', 150, 150, 90, '#FFFFFF', 'bathroom-fixtures', ARRAY['bathroom', 'ensuite'], 'Bath', 'Accessible walk-in bathtub with low step entry', '1.0.0', false, '{}', '{}'),
('bathroom-mirror-large', 'Large Bathroom Mirror', 'appliance', 80, 80, 100, '#C0C0C0', 'bathroom-props', ARRAY['bathroom', 'ensuite'], 'RectangleHorizontal', 'Large frameless bathroom mirror', '1.0.0', false, '{}', '{}'),
('bathroom-extractor-fan', 'Extractor Fan', 'appliance', 30, 30, 30, '#FFFFFF', 'bathroom-props', ARRAY['bathroom', 'ensuite'], 'Wind', 'Wall-mounted bathroom extractor fan', '1.0.0', false, '{}', '{}'),
('bathroom-heated-towel-rail', 'Heated Towel Rail', 'appliance', 60, 60, 120, '#C0C0C0', 'bathroom-props', ARRAY['bathroom', 'ensuite'], 'Zap', 'Electric heated towel rail', '1.0.0', false, '{}', '{}'),
('window-standard', 'Standard Window', 'window', 120, 15, 120, '#E6F3FF', 'windows', ARRAY['kitchen', 'bedroom', 'bathroom', 'living-room', 'office', 'dining-room', 'dressing-room', 'utility', 'under-stairs', 'media-wall', 'internal-doors', 'flooring'], 'Square', 'Standard window - 120cm x 120cm x 15cm', '1.0.0', false, '{}', '{}'),
('window-large', 'Large Window', 'window', 180, 15, 120, '#E6F3FF', 'windows', ARRAY['kitchen', 'bedroom', 'bathroom', 'living-room', 'office', 'dining-room', 'dressing-room', 'utility', 'under-stairs', 'media-wall', 'internal-doors', 'flooring'], 'Square', 'Large window - 180cm x 120cm x 15cm', '1.0.0', false, '{}', '{}'),
('window-bay', 'Bay Window', 'window', 240, 15, 120, '#E6F3FF', 'windows', ARRAY['kitchen', 'bedroom', 'bathroom', 'living-room', 'office', 'dining-room', 'dressing-room', 'utility', 'under-stairs', 'media-wall', 'internal-doors', 'flooring'], 'Square', 'Bay window - 240cm x 120cm x 15cm', '1.0.0', false, '{}', '{}'),
('window-small', 'Small Window', 'window', 80, 15, 80, '#E6F3FF', 'windows', ARRAY['kitchen', 'bedroom', 'bathroom', 'living-room', 'office', 'dining-room', 'dressing-room', 'utility', 'under-stairs', 'media-wall', 'internal-doors', 'flooring'], 'Square', 'Small window - 80cm x 80cm x 15cm', '1.0.0', false, '{}', '{}'),
('door-standard', 'Standard Door', 'door', 80, 4, 200, '#8B4513', 'doors', ARRAY['kitchen', 'bedroom', 'bathroom', 'living-room', 'office', 'dining-room', 'dressing-room', 'utility', 'under-stairs', 'media-wall', 'internal-doors', 'flooring'], 'DoorClosed', 'Standard door - 80cm x 200cm x 4cm', '1.0.0', false, '{}', '{}'),
('door-double', 'Double Door', 'door', 160, 4, 200, '#8B4513', 'doors', ARRAY['kitchen', 'bedroom', 'bathroom', 'living-room', 'office', 'dining-room', 'dressing-room', 'utility', 'under-stairs', 'media-wall', 'internal-doors', 'flooring'], 'DoorClosed', 'Double door - 160cm x 200cm x 4cm', '1.0.0', false, '{}', '{}'),
('door-sliding', 'Sliding Door', 'door', 120, 4, 200, '#8B4513', 'doors', ARRAY['kitchen', 'bedroom', 'bathroom', 'living-room', 'office', 'dining-room', 'dressing-room', 'utility', 'under-stairs', 'media-wall', 'internal-doors', 'flooring'], 'DoorClosed', 'Sliding door - 120cm x 200cm x 4cm', '1.0.0', false, '{}', '{}'),
('door-french', 'French Door', 'door', 140, 4, 200, '#8B4513', 'doors', ARRAY['kitchen', 'bedroom', 'bathroom', 'living-room', 'office', 'dining-room', 'dressing-room', 'utility', 'under-stairs', 'media-wall', 'internal-doors', 'flooring'], 'DoorClosed', 'French door - 140cm x 200cm x 4cm', '1.0.0', false, '{}', '{}'),
('flooring-hardwood', 'Hardwood Floor', 'flooring', 300, 300, 2, '#DEB887', 'flooring', ARRAY['kitchen', 'bedroom', 'bathroom', 'living-room', 'office', 'dining-room', 'dressing-room', 'utility', 'under-stairs', 'media-wall', 'internal-doors', 'flooring'], 'Layers', 'Oak hardwood flooring - 300cm x 300cm x 2cm', '1.0.0', false, '{}', '{}'),
('flooring-tile', 'Tile Floor', 'flooring', 300, 300, 2, '#D3D3D3', 'flooring', ARRAY['kitchen', 'bedroom', 'bathroom', 'living-room', 'office', 'dining-room', 'dressing-room', 'utility', 'under-stairs', 'media-wall', 'internal-doors', 'flooring'], 'Layers', 'Ceramic tile flooring - 300cm x 300cm x 2cm', '1.0.0', false, '{}', '{}'),
('flooring-carpet', 'Carpet Floor', 'flooring', 300, 300, 2, '#8FBC8F', 'flooring', ARRAY['kitchen', 'bedroom', 'bathroom', 'living-room', 'office', 'dining-room', 'dressing-room', 'utility', 'under-stairs', 'media-wall', 'internal-doors', 'flooring'], 'Layers', 'Carpet flooring - 300cm x 300cm x 2cm', '1.0.0', false, '{}', '{}'),
('flooring-vinyl', 'Vinyl Floor', 'flooring', 300, 300, 2, '#F0E68C', 'flooring', ARRAY['kitchen', 'bedroom', 'bathroom', 'living-room', 'office', 'dining-room', 'dressing-room', 'utility', 'under-stairs', 'media-wall', 'internal-doors', 'flooring'], 'Layers', 'Vinyl plank flooring - 300cm x 300cm x 2cm', '1.0.0', false, '{}', '{}'),
('utility-washing-machine', 'Utility Washing Machine', 'appliance', 60, 60, 85, '#f0f0f0', 'utility-appliances', ARRAY['utility'], 'Zap', 'Front-loading washing machine for utility area', '1.0.0', false, '{}', '{}'),
('utility-tumble-dryer', 'Utility Tumble Dryer', 'appliance', 60, 60, 85, '#e8e8e8', 'utility-appliances', ARRAY['utility'], 'Wind', 'Tumble dryer for utility area', '1.0.0', false, '{}', '{}'),
('utility-sink', 'Utility Sink', 'appliance', 60, 60, 90, '#FFFFFF', 'utility-appliances', ARRAY['utility'], 'Waves', 'Deep utility sink', '1.0.0', false, '{}', '{}')

ON CONFLICT (component_id) DO UPDATE SET
  name = EXCLUDED.name,
  type = EXCLUDED.type,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  color = EXCLUDED.color,
  category = EXCLUDED.category,
  room_types = EXCLUDED.room_types,
  icon_name = EXCLUDED.icon_name,
  description = EXCLUDED.description,
  version = EXCLUDED.version;

-- Re-enable RLS
ALTER TABLE public.components ENABLE ROW LEVEL SECURITY;

-- Success message
DO $$
BEGIN
  RAISE NOTICE '🌅 THE HORIZON IS HERE! Multi-room component library installed! 🏠';
  RAISE NOTICE 'Added 113 components across all room types';
  RAISE NOTICE 'Room types: bedroom, bathroom, living-room, dining-room, office, dressing-room, utility';
  RAISE NOTICE 'Categories: counter-tops, end-panels, bedroom-furniture, bedroom-storage, bathroom-vanities, bathroom-fixtures, media-furniture, media-storage, flooring-materials, living-room-furniture...';
  RAISE NOTICE 'Your design empire now spans the entire home! 🚀✨';
END $$;